// This file was generated by a python script.
// Do not edit this file... YOUR CHANGES WILL GET OVERWRITTEN...
// Edit proj/xdl_types.json instead.

#include "util/datatype1.hh"

 /*
   The list of XDL types specific to this application.
 */
using namespace std;
